/**
 * Issue Creator — Publication Overview plug-in for WoodWing Studio
 *
 * Plans a print issue and creates the layouts for it in one go: pick templates
 * for the empty page slots of the issue you are looking at, then push the whole
 * plan to Studio's Planning API (CreateLayouts on editorialplan.php), which
 * instantiates the layouts from their templates with the page numbers already
 * set. No InDesign involved, no file upload, no second login.
 *
 * Runs inside the Publication Overview child application (same-origin iframe)
 * where the PoUiSdk and the relayed ContentStationSdk globals are available.
 * The current brand / issue / edition come from PoUiSdk.currentFilterSetting(),
 * so the plug-in never asks the user what they are looking at.
 *
 * GENERATED FILE NOTICE: dist/issue-creator-plugin.js is generated by
 * build-plugin.js from the files in src/ — edit those and rebuild.
 *
 * Registration (WoodWing Cloud): Management Console → Integrations →
 * Plug-ins → Publication Overview → Add new → URL of the dist file.
 */
(function () {
  'use strict';

  var VERSION = '0.4.1';
  var TAG = '[issue-creator]';

  if (typeof PoUiSdk === 'undefined') {
    // Not in a Publication Overview context (or registered in the wrong plug-in
    // slot in the Management Console) — do nothing, never break the page.
    console.warn(TAG + ' PoUiSdk not available — plug-in not loaded in a Publication Overview context.');
    return;
  }
